services:
  user:
    container_name: dip_user
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - education
    volumes:
      - ./:/app

volumes:
  static:
  
networks:
  education:
    driver: bridge
    external: true
